:zap: [#2089] Use multithreading for Mijn Aanvragen list
maykinmedia/open-inwoner pull request #1015
Opened 2024-02-09 09:56 UTC by stevenbal

issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2089

Requires #995 to be merged first

2024-02-12 17:26 UTC, alextreme commented
Surprised it didn't cause more problems with the testsuite :see_no_evil: 
What do you think @pi-sigma and @Bartvaderkin ?

2024-02-13 09:50 UTC, Bartvaderkin requested changes

2024-02-13 10:59 UTC, stevenbal commented on src/open_inwoner/openzaak/tests/test_cases_cache.py
> +            self.client.force_login(user=self.user)
You're right, I'll remove the duplicate `force_login`s

2024-02-13 15:26 UTC, pi-sigma approved these changes

2024-02-14 10:17 UTC, Bartvaderkin approved these changes
Threading can be spicy but let's go for it.

2024-02-14 10:21 UTC, merged