:sparkles: [#2088] Implement Zaken search for eHerkenning users
maykinmedia/open-inwoner pull request #1030
Opened 2024-02-15 12:51 UTC by stevenbal

issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2088

2024-02-15 14:20 UTC, Bartvaderkin requested changes
Some small notes.

2024-02-15 14:20 UTC, Bartvaderkin commented on src/open_inwoner/openzaak/clients.py
> +        if user_bsn:
For correctness we could check if not both `user_bsn` and `user_kvk_or_rsin` are supplied as they're mutually exclusive. Or `vestigingsnummer` and `user_bsn` etc.

Also some typing in the signature would be good.

2024-02-15 14:20 UTC, Bartvaderkin commented on src/open_inwoner/openzaak/utils.py
> +def get_fetch_parameters(request) -> dict:
Good idea to clean this up. Maybe use a name like `get_user_fetch_parameters()` so we keep it for user-related params only?

2024-02-15 14:20 UTC, Bartvaderkin commented on src/open_inwoner/search/views.py
> +        if search_params := get_fetch_parameters(self.request):
Here you see it's unclear: this makes get_fetch_parameters() look like magic. We're getting the fetch params for the user, not a generic mystery search.

2024-02-16 11:44 UTC, Bartvaderkin requested changes

2024-02-16 13:35 UTC, stevenbal commented on src/open_inwoner/openzaak/clients.py
> +        ), "either `user_bsn` or `user_kvk_or_rsin`/`vestigingsnummer` should be supplied, not both"
Oh TIL, I always assumed `Optional` was for optional arguments, but you're right

2024-02-21 08:16 UTC, Bartvaderkin approved these changes

2024-02-22 08:38 UTC, merged