[#2145] Registration notifications redesign
maykinmedia/open-inwoner pull request #1065
Opened 2024-02-29 14:49 UTC by jiromaykin

issue related to Design: https://www.figma.com/file/iKGhWhstaLIlFSaND2q7cE/OIP---Designs-(new)?type=design&node-id=270%3A6788&mode=design&t=1dHj3fYwwXbn6jvn-1

Issue showing difference: https://taiga.maykinmedia.nl/project/open-inwoner/task/2145

2024-03-25 11:50 UTC, pi-sigma requested changes
When I deselect one of the options, the text becomes underlined. It stays that way when I re-select the option and only disappears when click outside the card.

![Screenshot from 2024-03-25 12-35-01](https://github.com/maykinmedia/open-inwoner/assets/89185369/2fc3ffcd-b249-4f78-b2bd-1df4f4fcf958)

Is this intended?

Also, wouldn't it make sense to use the same design for changing notification prefs in the profile?

2024-03-25 11:50 UTC, pi-sigma commented on src/open_inwoner/js/components/form/ChoiceListMultiple.js
> +    // If selector exists
Update/remove comment

2024-03-26 08:40 UTC, pi-sigma approved these changes

2024-03-28 18:37 UTC, alextreme commented
> Attentie @alextreme : This one has been approved, but... here i assumed that checkboxes have to wrap both the Label and the info text - and we may not want that (?) because of the future checkbox designs.

If you want to revisit this feel free to do so, I've removed Paul's approval

2024-04-04 13:02 UTC, jiromaykin commented
@Bartvaderkin @pi-sigma I've removed the `...p {{ help_extra_cls }}` class from the Checkbox template since I think it's superfluous.

2024-04-08 16:25 UTC, jiromaykin commented
@pi-sigma This one is now fully ready for review.

2024-04-09 10:34 UTC, pi-sigma requested changes
Why is the siteimprove commit part of this PR? Otherwise looking good.

2024-04-09 10:46 UTC, jiromaykin commented
> Why is the siteimprove commit part of this PR? Otherwise looking good.

Just a little explanation for future questions: The Siteimprove tracker has to track _extremely_ specific elements in the site. Like, for example, the second checkbox inside a list of 3. So if the structure/class of the tracked element changes, I will also have to update the tracker code... It's going to be a 'challenge' to not forget to do this with future changes.

2024-04-11 12:52 UTC, merged