[#2169] Improve mail-template styling
maykinmedia/open-inwoner pull request #1072
Opened 2024-03-04 13:12 UTC by jiromaykin

detailed issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2169

overall issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2134

2024-03-05 15:11 UTC, Bartvaderkin requested changes

2024-03-05 15:11 UTC, Bartvaderkin commented on src/open_inwoner/templates/mail/_base.html
> +        border: 1px solid{{ theming.primary_color }};
There should be a space between `solid` and the `{{`

2024-03-05 16:27 UTC, jiromaykin commented on src/open_inwoner/templates/mail/_base.html
> +        margin: 0;
We need this margin on the base template Body in order to get rid of default spacing ~ which in the issue from Groningen was mentioned as "Gele/blauwe vlak zou over hele breedte van het scherm, is nu als deel" which was a bit weirdly worded but this margin was causing it.

2024-03-07 11:01 UTC, pi-sigma requested changes
Template language should be consistent

2024-03-07 11:05 UTC, jiromaykin commented on src/open_inwoner/conf/parts/expiring_plan.html
>  <p><a href="{{ plan_list_link }}">Go to your plans</a></p>
Probably, but this PR for #2169 is really only about styling and about the 3 case_status templates; I'd rather change all the 'other templates properly in task #2120 -  I just wanted to do a small correction for the paragraphs here.

2024-03-07 15:54 UTC, pi-sigma approved these changes

2024-03-08 11:27 UTC, Bartvaderkin approved these changes

2024-03-11 09:03 UTC, alextreme commented
Mag gemerged worden na verhelpen conflict

2024-03-11 11:27 UTC, merged