[#2106] Implemented 'contactform_confirmation' email
maykinmedia/open-inwoner pull request #1106
Opened 2024-03-21 12:40 UTC by Bartvaderkin

The generic contact form code is pretty spicy. I tried refactoring but it does need to do a lot so except some small changes I kept it this way.

2024-03-25 10:45 UTC, stevenbal approved these changes

2024-03-25 12:03 UTC, pi-sigma approved these changes

2024-04-02 11:08 UTC, alextreme requested changes
Rename admin setting

2024-04-02 11:08 UTC, alextreme commented on src/open_inwoner/openklant/migrations/0011_openklantconfig_api_sends_email_confirmation.py
> +                default=False,
Lets turn this around to make the usage via the admin simpler: "Stuur contactformulier e-mailbevestiging" / "send_email_confirmation" which is off by default.

2024-04-18 11:14 UTC, alextreme approved these changes

2024-04-18 11:14 UTC, merged