Fix klant creation with e-suite
maykinmedia/open-inwoner pull request #1123
Opened 2024-03-28 12:02 UTC by pi-sigma

Taiga: [#2221](https://taiga.maykinmedia.nl/project/open-inwoner/task/2221)

2024-04-02 14:28 UTC, stevenbal requested changes

2024-04-02 14:28 UTC, stevenbal commented on src/open_inwoner/openklant/clients.py
> +    def _create_klant_for_bsn(self, user_bsn: str) -> Klant:
The same occurs for eHerkenning, is this an issue on the side of eSuite?

2024-04-02 14:28 UTC, stevenbal commented on src/open_inwoner/openklant/services.py
> +        msg = "created klant (%s) for user" % klant.klantnummer
could be an f-string, but not really an issue

2024-04-02 14:28 UTC, stevenbal commented on src/open_inwoner/openklant/tests/test_signal.py
> +        )
If this log is present, it does imply that things worked, but I would also add assertions to check that `m.request_history` contains the expected requests (one for the GET and one for the POST, and no others)

2024-04-02 14:28 UTC, stevenbal commented on src/open_inwoner/openklant/tests/test_signal.py
> +        )
same comment as above

2024-04-02 14:28 UTC, stevenbal commented on src/open_inwoner/openklant/tests/test_views.py
> +            kwargs={"kcm_uuid": uuid_from_url(data.klant_contactmoment["uuid"])},
I think you forgot to remove the `uuid` from the `klant_contactmoment` (applies to other cases in this test file as well)

2024-04-03 08:55 UTC, pi-sigma commented on src/open_inwoner/openklant/clients.py
> +    def _create_klant_for_bsn(self, user_bsn: str) -> Klant:
Same here. The mock for information retrieval that's needed for testing user creation on the side of the E-suite is disabled.

2024-04-03 10:50 UTC, pi-sigma commented
By default, `requests_mock` forces query params to be lower case  (see [https://requests-mock.readthedocs.io/en/latest/knownissues.html](https://requests-mock.readthedocs.io/en/latest/knownissues.html)). I thought it would be good to change that, since whether or not query params are considered case sensitive is not settled by RFC; it seems to depend on the application. We have other tests (`CaseListViewTests`) that could also be updated.

2024-04-03 12:10 UTC, pi-sigma commented on src/open_inwoner/openklant/clients.py
> +    def _create_klant_for_bsn(self, user_bsn: str) -> Klant:
With the mock enabled, things work as expected. Calls to the Klanten and Contactmomenten APIs return `200`/`201`, the klant shows up in the E-suite, question is created and linked to the new user.

![post-success](https://github.com/maykinmedia/open-inwoner/assets/89185369/c46667b3-bc0e-4187-9a5d-0c89540369f9)

2024-04-04 07:27 UTC, Bartvaderkin approved these changes

2024-04-04 07:27 UTC, Bartvaderkin commented on src/open_inwoner/utils/test.py
> +    return url.split("/")[-1]
This could ideally do some checks to see if the bit looks like a UUID.

2024-04-04 08:20 UTC, stevenbal approved these changes

2024-04-08 09:40 UTC, stevenbal commented
Tested it just now, works both for BSN and KVK :+1:

2024-04-08 09:42 UTC, merged