[#2176] First pass at setting up docs builder
maykinmedia/open-inwoner pull request #1166
Opened 2024-04-19 11:01 UTC by Bartvaderkin

- Config and CI workflow inspired by open-forms
- Kept current old docs for now but fixed main issues

PR mostly to test CI

2024-04-25 14:34 UTC, stevenbal requested changes
Looks good overall, couple of comments/questions

2024-04-29 07:16 UTC, Bartvaderkin commented on .github/workflows/ci.yml
> +          - 9300:9300
Technically not, but the builder setups Django and then starts generating logs etc.

I'll see if we can get rid of that, would be handy.

2024-04-29 07:17 UTC, Bartvaderkin commented on docs/coding_style/index.rst
>  the `backend <coding_style_backend>`.
We'll probably remove these but good catch.

2024-04-29 07:18 UTC, Bartvaderkin commented on .readthedocs.yaml
> +#      - bash bin/rtd_post_checkout.sh
Maybe, but I'll remove it and we can re-steal it if we need it.

2024-05-23 09:40 UTC, pi-sigma approved these changes

2024-05-23 13:01 UTC, merged