[#2322] Added Celery and Celery-beat
maykinmedia/open-inwoner pull request #1186
Opened 2024-04-29 09:25 UTC by Bartvaderkin

2024-05-24 14:22 UTC, pi-sigma approved these changes

2024-05-24 17:15 UTC, alextreme commented on src/open_inwoner/conf/base.py
> +    "dummy_wait_task": {
Lets perform the zgw_import_data task every morning at 07:00 to replace the cronjob

2024-05-24 17:51 UTC, alextreme requested changes
Nearly there, a few final remarks. And we need to update deployment + helm charts, but thats for a separate PR

2024-05-27 08:08 UTC, alextreme approved these changes

2024-05-27 08:09 UTC, alextreme commented
Can be merged after CI is green

2024-05-27 08:57 UTC, merged