[#2344] Add text alternatives for meaningful icons
maykinmedia/open-inwoner pull request #1254
Opened 2024-06-13 08:10 UTC by jiromaykin

icons need to remain hidden for screenreaders (aria-hidden=true) because material-cons and font-awesome etc. do not provide proper meaningful text, so to add meaning we add a span with the visually hidden sr-only class.

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2344

2024-06-13 08:11 UTC, jiromaykin commented
@alextreme suggesties voor betere teksten zijn welkom.

2024-06-17 13:57 UTC, pi-sigma requested changes

2024-06-17 13:57 UTC, pi-sigma commented on src/open_inwoner/templates/pages/cases/statuses.html
> +                    <span class="sr-only">{% trans 'Niet voltooid' %}</span>
Let's stick to one kind of quotes unless we need to depart.

2024-06-17 13:57 UTC, pi-sigma commented on src/open_inwoner/templates/pages/cases/statuses.html
> +                    <span class="sr-only">{% trans 'Voltooid' %}</span>
```suggestion
                    <span class="sr-only">{% trans "Voltooid" %}</span>
```

2024-06-17 13:57 UTC, pi-sigma commented on src/open_inwoner/templates/pages/cases/statuses.html
> +                <span class="sr-only">{% trans 'Toekomstige status' %}</span>
```suggestion
                <span class="sr-only">{% trans "Toekomstige status" %}</span>
```

2024-06-17 13:57 UTC, pi-sigma commented on src/open_inwoner/templates/pages/cases/statuses.html
> +                <span class="sr-only">{% trans 'Toekomstige voltooide status' %}</span>
```suggestion
                <span class="sr-only">{% trans "Toekomstige voltooide status" %}</span>
```

2024-06-17 14:33 UTC, jiromaykin commented on src/open_inwoner/templates/pages/cases/statuses.html
> +                    <span class="sr-only">{% trans 'Niet voltooid' %}</span>
Oh well... Looking at the rest of the entire project there's quite some mixed use of quotes in these translation blocks, sometimes even within the same file (like in 'Plans>Preview') but I don't mind changing it here.

2024-06-18 08:54 UTC, pi-sigma approved these changes

2024-06-18 08:59 UTC, merged