♿ [#2352] Remove faulty aria-label and add external link
maykinmedia/open-inwoner pull request #1257
Opened 2024-06-13 14:03 UTC by jiromaykin

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2343

This approach ensures that screen readers can read both the visible link text (inside the a-href anchor) _**and**_ the additional information about the link opening a new/different website, which is information coming from the meaningful icon.

2024-06-14 08:20 UTC, alextreme commented
Assigning to Paul for review next week, requires a double-check

2024-06-17 13:53 UTC, pi-sigma requested changes

2024-06-17 13:53 UTC, pi-sigma commented on src/open_inwoner/utils/ckeditor.py
> +                # Append both elements to the anchor
Comment is unnecessary, the code is self-explanatory.

2024-06-17 13:53 UTC, pi-sigma commented on src/open_inwoner/utils/ckeditor.py
> +                sr_only_text = soup.new_tag("span")
Comment is unnecessary. Add a newline between the `icon` code and this part, and make the code self-explanatory by using a more explicit variable name (e.g. `screen_reader_only_text`. It's more verbose but we only use it here so it's ok)

2024-06-17 14:31 UTC, pi-sigma approved these changes

2024-06-17 15:24 UTC, merged