[#2340] Header/footer logo use alt from image configuration
maykinmedia/open-inwoner pull request #1260
Opened 2024-06-17 15:44 UTC by jiromaykin

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2340

Both the header logo and the footer logo need to use the same ALT that can be set in the Admin in the '**mappen**' configuration: http://localhost:8000/admin/filer/folder/

Each image in there (navigate to any in the mappen/directories) has an 'ALT' field that can be set - but when empty the image will just receive value from the Site Name.

<img width="1347" alt="Screenshot 2024-06-17 at 17 41 58" src="https://github.com/maykinmedia/open-inwoner/assets/118177951/efa113db-cc2b-49c9-abae-9a9cefe4a448">

2024-06-17 15:46 UTC, jiromaykin commented on src/open_inwoner/utils/context_processors.py
> +            "logo_alt": config.logo.default_alt_text,
@pi-sigma Not sure I am using the correct approach here... Not quite sure why this value is set differently for the footer anyway 
(would this just be for emailtemplates?)

2024-06-18 09:55 UTC, pi-sigma requested changes

2024-06-18 09:55 UTC, pi-sigma commented on src/open_inwoner/templates/master.html
> +                    {% firstof config.logo.default_alt_text config.name as logo_alt_text %}
```suggestion
                    {% firstof config.footer_logo.default_alt_text config.name as logo_alt_text %}
```

2024-06-18 14:31 UTC, pi-sigma approved these changes

2024-06-18 15:57 UTC, merged