[#2537] Implement a multi-zgw backend proxy to the individual clients
maykinmedia/open-inwoner pull request #1281
Opened 2024-06-26 10:53 UTC by swrichards

2024-06-27 10:55 UTC, pi-sigma requested changes

2024-06-27 10:55 UTC, pi-sigma commented on src/open_inwoner/openzaak/clients.py
> +        """Joins results for all successful responses in a list."""
The previous docstring is imperative, this one declarative. We should stick to one standard. I prefer the imperative style, though don't have strong feelings about it.

2024-06-27 10:55 UTC, pi-sigma commented on src/open_inwoner/openzaak/clients.py
> +                exception: Exception = None
```suggestion
                exception: Exception | None = None
```

2024-06-27 10:55 UTC, pi-sigma commented on src/open_inwoner/openzaak/clients.py
> +                    exception: Exception | None = task.exception()
Do we need to repeat the type annotation?

2024-06-27 10:55 UTC, pi-sigma commented on src/open_inwoner/openzaak/clients.py
> +                except Exception as exc:
`exc` is not used

2024-06-27 10:55 UTC, pi-sigma commented on src/open_inwoner/openzaak/clients.py
> +            responses=sorted(
Why create a new list if the old one is not used? `responses.sort(..)` would work the same (and faster).

2024-06-27 10:55 UTC, pi-sigma commented on src/open_inwoner/openzaak/clients.py
> +        return None
I wonder if it would be preferable to raise an exception if the attempt is made to build a `form_client` but the `form_service` is not configured.

2024-06-27 10:55 UTC, pi-sigma commented on src/open_inwoner/openzaak/exceptions.py
> +    """A container for exceptions raise within individual client requests."""
```suggestion
    """A container for exceptions raised within individual client requests."""
```

2024-06-27 10:55 UTC, pi-sigma commented on src/open_inwoner/openzaak/exceptions.py
> +            "One of more ZGW clients raised an error",
```suggestion
            "One or more ZGW clients raised an error",
```

2024-06-27 10:55 UTC, pi-sigma commented on src/open_inwoner/openzaak/exceptions.py
> +    def derive(self, exceptions: Sequence[Exception]):
```suggestion
    def derive(self, exceptions: Sequence[Exception]) -> MultiZgwClientProxyError:
```

2024-06-27 10:55 UTC, pi-sigma commented on src/open_inwoner/openzaak/tests/test_clients.py
>          ):
Did you consider using subtests for the individual cases (same in the following test)?

2024-06-27 10:55 UTC, pi-sigma commented on src/open_inwoner/openzaak/tests/test_clients.py
> +        self.a_url = "http://foo/bar/rows"
```suggestion
        self.url_1 = "http://foo/bar/rows"
```

2024-06-27 10:55 UTC, pi-sigma commented on src/open_inwoner/openzaak/tests/test_clients.py
> +        self.another_url = "http://bar/baz/rows"
```suggestion
        self.url_2 = "http://bar/baz/rows"
```
If it's not possible to use descriptive variable names (and I can't think of anything here), I'd prefer indexed names.

2024-06-27 10:55 UTC, pi-sigma commented on src/open_inwoner/openzaak/tests/test_clients.py
> +        m.get(self.another_url, json=["bar", "baz"])
See previous comments about the variables

2024-06-27 13:50 UTC, pi-sigma approved these changes

2024-06-28 10:24 UTC, alextreme commented on src/open_inwoner/openzaak/clients.py
> +    @cached_property
I'm not sure this is workable in the context of uwsgi, where we have threading active within the same process. In-memory caching without taking this into account is a bit of a minefield, please err on the side of caution considering our domain

2024-07-01 08:19 UTC, alextreme approved these changes

2024-07-01 08:19 UTC, merged