[#2668] Translations sprint 25
maykinmedia/open-inwoner pull request #1352
Opened 2024-08-15 09:49 UTC by jiromaykin

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2668

2024-08-15 17:25 UTC, alextreme requested changes
Paar punten ter verbetering

2024-08-15 17:25 UTC, alextreme commented on src/open_inwoner/conf/locale/nl/LC_MESSAGES/django.po
> +msgstr "Hoe wilt u meldingen over cases ontvangen?"
hier zou ik 'aanvragen' of 'zaken' verwachten, maar niet 'cases'

2024-08-15 17:25 UTC, alextreme commented on src/open_inwoner/conf/locale/nl/LC_MESSAGES/django.po
> +msgstr ""
"De link die u gebruikte is verlopen. Uw aanvraag is via onderstaand overzicht te vinden."

2024-08-15 17:25 UTC, alextreme commented on src/open_inwoner/conf/locale/nl/LC_MESSAGES/django.po
> +msgstr "Activeer keuzemogelijkheid voor notificiatie kanaal"
typo

2024-08-15 17:25 UTC, alextreme commented on src/open_inwoner/conf/locale/nl/LC_MESSAGES/django.po
> +msgstr "De zaakidentificatie"
Lijkt me onjuist

2024-08-16 08:56 UTC, alextreme approved these changes

2024-08-16 08:57 UTC, alextreme requested changes
Whoops, 2 testen falen nog, kijk er maandag even naar: 

FAIL: test_login_for_inactive_user_shows_appropriate_message (open_inwoner.accounts.tests.test_auth.TestLoginLogoutFunctionality.test_login_for_inactive_user_shows_appropriate_message)

AssertionError: ['Voer een juiste E-mailadres en wachtwoord in. Let op da[37 chars]jn.'] != ['Voer een juist E-mailadres en wachtwoord in. Let op dat[36 chars]jn.']

======================================================================
FAIL: test_login_with_wrong_credentials_shows_appropriate_message (open_inwoner.accounts.tests.test_auth.TestLoginLogoutFunctionality.test_login_with_wrong_credentials_shows_appropriate_message)

2024-08-19 13:03 UTC, alextreme approved these changes

2024-08-19 14:56 UTC, jiromaykin commented on src/open_inwoner/conf/locale/nl/LC_MESSAGES/django.po
>  msgid_plural "%d stories were successfully marked as deleted."
Je bedoelt 'stories'? Ik zag hetzelfde verschijnsel bij een zelfde door Bart gemaakte actions/stories constructie bij de vertalingen. Geen idee waar de term 'stories' vandaan komt, die zijn ws. allemaal 'action/actions'

2024-08-19 15:01 UTC, jiromaykin commented on src/open_inwoner/conf/locale/nl/LC_MESSAGES/django.po
>  "Voer een juiste E-mailadres en wachtwoord in. Let op dat beide velden "
@swrichards Die aparte PR zou je dan misschien moeten branchen vanaf deze, want anders krijg je wellicht dezelfde PO/MO conflicten en fails als ik :-O

2024-08-19 15:15 UTC, jiromaykin commented on src/open_inwoner/conf/locale/nl/LC_MESSAGES/django.po
> +msgstr ""
Deze doe ik dan nog wel even en dan geef ik 't op :-)

2024-08-20 06:40 UTC, merged