[#2737] Sync user personal data with OpenKlant2
maykinmedia/open-inwoner pull request #1396
Opened 2024-09-12 12:26 UTC by swrichards

[Taiga 2737](https://taiga.maykinmedia.nl/project/open-inwoner/task/2737)

2024-09-13 12:08 UTC, pi-sigma requested changes

2024-09-13 12:08 UTC, pi-sigma commented on src/open_inwoner/openklant/tests/helpers.py
> +            "use_live_service": bool(os.getenv("RECORD_OPENKLANT_CASSETTES"))
For `RECORD_OPENKLANT_CASSETTES=False`, `bool(os.getenv("RECORD_OPENKLANT_CASSETTES"))` will evaluate to `True`. I think that's confusing.

2024-09-13 12:08 UTC, pi-sigma commented on src/open_inwoner/openklant/tests/helpers.py
> +                if bool(os.getenv("RECORD_OPENKLANT_CASSETTES"))
See previous comment

2024-09-16 15:41 UTC, pi-sigma approved these changes
Minor question, but we can go ahead

2024-09-16 15:41 UTC, pi-sigma commented on src/open_inwoner/openklant/services.py
> +        if len(
What's the reason for checking `len` instead of just truthiness of `email_adressen` (and `phone_adressen` below)?

2024-09-17 10:21 UTC, pi-sigma approved these changes

2024-09-17 12:14 UTC, merged

2024-09-17 12:17 UTC, alextreme commented on src/open_inwoner/openklant/services.py
> +                # TODO: Is this a use-case? The API seems to allow this
This seems like a valid issue for OK, good that you already raised it: https://github.com/maykinmedia/open-klant/issues/241