[#2862] Integrate OpenKlant2 service with contactmoment detail view
maykinmedia/open-inwoner pull request #1490
Opened 2024-11-07 13:41 UTC by pi-sigma

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2862

2024-11-20 10:16 UTC, swrichards requested changes
Looks good, big push here. Mostly small'ish comments.

2024-11-20 10:16 UTC, swrichards commented on src/open_inwoner/openklant/services.py
> +    # url: str
Legacy?

2024-11-20 10:16 UTC, swrichards commented on src/open_inwoner/openklant/services.py
> +
Hello!

2024-11-20 10:16 UTC, swrichards commented on src/open_inwoner/openklant/services.py
> +            # ),
```suggestion

```

2024-11-20 10:16 UTC, swrichards commented on src/open_inwoner/openklant/services.py
> +            # "status": str(Status.safe_label(kcm.contactmoment.status, _("Onbekend"))),
```suggestion
```

2024-11-20 10:16 UTC, swrichards commented on src/open_inwoner/openklant/services.py
> +                    # url="",
Indeed, I guess it makes sense for the views to handle that: they decide which view names they want to use, this just provides the parameters and doesn't have knowledge of how it will be used in the view layer.

2024-11-20 10:16 UTC, swrichards commented on src/open_inwoner/openklant/services.py
> +        )
I feel a bit uncomfortable having this here in the service: this model is only needed to support logic in the view, and is thus a purely a presentation-layer concern. Would there be a way to omit the "new answer available" key from the DTO, and add that only in the view?

It seems to me we should be able to use  `KlantContactMomentAnswer` in a generic way (e.g. it only needs a url and user, both of which are available in the view without having to know much more).

2024-11-20 10:16 UTC, swrichards commented on src/open_inwoner/openklant/services.py
> +    def _reformat_question(
Here and above, I'd prefer a name such as `_build_question_dto` (we could even, if we don't have to use `KlantContactMomentAnswer` here, make this a method on `OpenKlant2Question`, which might be even neater, so you get:

```
question_ok2.to_question_dto()
```

2024-11-20 10:16 UTC, swrichards commented on src/open_inwoner/openklant/tests/factories.py
> +) -> dict:
We could type this as a `Question` and validate here as well.

2024-11-20 10:16 UTC, swrichards commented on src/open_inwoner/templates/pages/questions/questions.html
As discussed: perhaps move these to `src/open_inwoner/templates/pages/partials`

2024-11-20 10:16 UTC, swrichards commented on src/open_inwoner/utils/url.py
> +    return uuid.UUID(uuid_str)
This seems to assume a URL has a very specific shape: `http://foo/bar/{uuid}/` but might fail for  `http://foo/bar/{uuid}/bar-detail`.

I think a full regex would be better here, to just match the UUID directly and perhaps raise if more than one UUID is found to avoid subtle bugs where we match the wrong uuid, as we might in nested resources. (Alternatively, return all found UUIDs and let the caller handle the >1 case).

2024-11-20 10:16 UTC, swrichards commented on src/open_inwoner/openklant/services.py
> +        user: User,  # is this needed?
I think you're right that we don't: we just use the fetch params. I vaguely recall we might have needed it for cases to check the confidentiality level or some such, but we can always reintroduce it (and then just pass that directly, rather than the user). Happy to remove this from the protocol.

2024-11-20 10:16 UTC, swrichards commented on src/open_inwoner/openklant/tests/test_esuite_vragen_service.py
> +                # )
As per other comment, here and elsewhere: no indeed, let the view build the URLs, it's not a service level concern. The service should just provide the identifiers.

2024-11-22 10:21 UTC, pi-sigma commented on src/open_inwoner/openklant/services.py
> +    # url: str
Indeed

2024-11-22 11:22 UTC, pi-sigma commented on src/open_inwoner/utils/url.py
> +    return uuid.UUID(uuid_str)
I added a parameter to allow multiple matches which defaults to `False` and raises `ValueError`. Not 100% sure what to do if no match is found. Raise or return `None`? I went for the second option, but could go the other way as well.

2024-11-22 11:57 UTC, pi-sigma commented on src/open_inwoner/openklant/services.py
> +        user: User,  # is this needed?
On the other hand, the eSuite service needs the `User` to fetch the relevant data. Although `OpenKlant2Service` doesn't need it for `retrieve_question`, we would need to change the logic and distinguish between the two services whenever we retrieve a single question. Though perhaps that's the way to go if the methods are different with regard to (not) requiring the `User` as argument?

2024-11-25 10:29 UTC, swrichards commented on src/open_inwoner/utils/url.py
> +    matches = re.findall(pattern, url, re.IGNORECASE)
Given that this is likely to be called in loops, we could pre-compile:

```suggestion

_UUID_PATTERN = re.compile(r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")

def uuid_from_url(
    url: str, allow_multiple: bool = False
) -> uuid.UUID | list[uuid.UUID] | None:
    """Extract UUID(s) from a given URL"""

    matches = _UUID_PATTERN.findall(pattern, url, re.IGNORECASE)
```

2024-11-25 10:29 UTC, swrichards commented on src/open_inwoner/utils/url.py
> +        )
The cases seem a bit confusing to me, as both branches are special cases if `len(matches) > 1`:

```suggestion
    if len(matches) > 1:
        if allow_multiple:
          return [uuid.UUID(match) for match in matches]

        raise ValueError(
            "url contains more than 1 UUID (use allow_multiple=True if you expect multiple results)"
        )
```

2024-11-25 10:29 UTC, swrichards commented on src/open_inwoner/utils/url.py
> +    return uuid.UUID(uuid_str)
Good solution, just a small nitpick about the conditional.

2024-11-25 10:31 UTC, swrichards commented on src/open_inwoner/openklant/services.py
> +        user: User,  # is this needed?
I think its fine to provide it as context to both, I'd say the general approach is maximalist: we provide as much context as required by the most demanding implementation.

2024-11-25 10:32 UTC, swrichards requested changes
LGTM, just one or two nitpicks, and the outstanding issue about integrating the seen status into the service.

2024-11-25 14:39 UTC, pi-sigma commented on src/open_inwoner/openklant/services.py
> +        )
Ticket: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2901

2024-11-25 14:43 UTC, swrichards approved these changes

2024-11-28 14:36 UTC, alextreme commented
Can be merged after rebase from Paul and final check

2024-11-28 16:43 UTC, swrichards approved these changes

2024-11-28 17:19 UTC, merged