[#2871] Use composite natural key (domein, rsin) for CatalogusConfig
maykinmedia/open-inwoner pull request #1497
Opened 2024-11-14 14:07 UTC by pi-sigma

A composite key is used for CatalogusConfig to support import/export of ZGW objects across different environments (where the url is different)

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2871

2024-11-26 14:22 UTC, swrichards commented on src/open_inwoner/openzaak/zgw_imports.py
>                      continue
As discussed, I don't think there is a need to change these: the actual API import _should_ use the URL, UUID, etc.

2024-11-26 14:22 UTC, swrichards commented on src/open_inwoner/openzaak/tests/test_zgw_imports_command.py
These changes might now be redundant too.

2024-11-26 14:22 UTC, swrichards commented on src/open_inwoner/openzaak/import_export.py
> +        ]:
```suggestion
        if source_config in {
            ZaakTypeStatusTypeConfig,
            ZaakTypeResultaatTypeConfig,
            ZaakTypeInformatieObjectTypeConfig,
        }:
```

2024-11-26 14:22 UTC, swrichards commented on src/open_inwoner/openzaak/import_export.py
> +                pass
```suggestion
            if field_name in exclude_fields:
                continue
```

2024-11-26 14:22 UTC, swrichards commented on src/open_inwoner/openzaak/import_export.py
> +            target.save()
This could perhaps itself be a helper method, given we use it a few times?

2024-11-26 14:22 UTC, swrichards commented on src/open_inwoner/openzaak/import_export.py
> +        raise ZGWImportError.from_exception_and_jsonl(exc, jsonl)
```suggestion
    except (source_config.MultipleObjectsReturned, source_config.DoesNotExis) as exc:
        raise ZGWImportError.from_exception_and_jsonl(exc, jsonl)
```

2024-11-26 14:22 UTC, swrichards commented on src/open_inwoner/openzaak/import_export.py
> +                pass
I generally feel there is a fair bit of duplication in these functions. I wonder whether we couldn't simply inline all of these functions in the `match` statement of the main loop, whereby each branch would define the target and the exclude fields, and then the loop would only do the updating logic once.

2024-11-26 14:22 UTC, swrichards commented on src/open_inwoner/openzaak/import_export.py
> +                pass
(I guess the related object handling is slightly different, no worries if it's too much hassle, but it might make sense to mark the functions as private with the `_` prefix).

2024-11-26 14:22 UTC, swrichards commented on src/open_inwoner/openzaak/admin.py
> +                            "imported are reported below."
```suggestion
                            "%(num_rows)d item(s) processed in total, with %(erroring_rows)d failing rows.
```

2024-11-26 14:22 UTC, swrichards commented on src/open_inwoner/openzaak/admin.py
> +                            "imported are reported below."
We could then perhaps vary `messages.SUCCESS` to be a warning if there are `>0` failing rows, so it's immediately obvious that something went _kind of_ ok, but not completely.

2024-11-26 14:22 UTC, swrichards commented on src/open_inwoner/openzaak/admin.py
> +                            f"<ol> {error_msg_html} </ol>"
```suggestion
                            _("It was not possible to import the following items:") + f"<ol> {error_msg_html} </ol>"
```

2024-11-26 14:22 UTC, swrichards commented on src/open_inwoner/openzaak/import_export.py
> +        return self.__str__()
Not sure the `text` property adds much over the default `__str__` that's already implemented.

2024-11-26 15:16 UTC, swrichards requested changes
Nice work, few suggestions here and there.

2024-11-26 15:16 UTC, swrichards commented on src/open_inwoner/openzaak/tests/test_import_export.py
> -                CatalogusConfigImport.from_jsonl_stream_or_string(bad_type)
I think this test is still valid?

2024-11-26 15:16 UTC, swrichards commented on src/open_inwoner/openzaak/tests/test_import_export.py
> -                )
Technically still a valid test, though we may want to assert that all the returned imports are the same.

2024-11-26 15:16 UTC, swrichards commented on src/open_inwoner/openzaak/tests/test_import_export.py
> +    def test_import_jsonl_update_report_duplicates(self):
```suggestion
    def test_import_jsonl_update_reports_duplicates(self):
```

2024-11-26 15:16 UTC, swrichards commented on src/open_inwoner/openzaak/tests/test_import_export.py
> +            pass
maybe a `self.assertRaises` to actualy ensure we got an error.

2024-11-26 15:16 UTC, swrichards commented on src/open_inwoner/openzaak/tests/test_import_export.py
As discussed, I think we need a test that validates a source and target scenario with (1) corresponding natural keys (e.g. all objects are found in the target) but (2) _differing_ values for URLs, zaaktype UUIDs, etc.,, and that the (3) latter values are not amended in the update (because those will point to the targets ZGW backend and should remain the same).

2024-11-27 11:37 UTC, pi-sigma commented on src/open_inwoner/openzaak/import_export.py
> +                pass
I moved the `exclude_fields` into the match statement, which makes the helper functions slimmer. I'm not sure more inlining would improve readability further, due to the difference between `CatalogusConfig`, `ZaaktypeConfig`, and the nested configs (the match statement would get pretty crowded).

2024-11-27 13:29 UTC, swrichards approved these changes

2024-11-28 10:30 UTC, merged