[#2903] Support export of only select ZaakType configs
maykinmedia/open-inwoner pull request #1503
Opened 2024-11-26 13:46 UTC by pi-sigma

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2903

2024-12-03 11:26 UTC, swrichards requested changes
An architectural question before I proceed, but TLDR: I think we can perhaps make this simpler by just adding another factory method to `CatalogusConfigExport` (and renaming it).

2024-12-03 11:26 UTC, swrichards commented on src/open_inwoner/openzaak/import_export.py
> +class ZGWConfigExport:
I am not sure we need to have inheritance here. I think the more obvious change would to:

1. Rename the existing `CatalogusConfigExport` to `ZGWConfigExport`
2. Add a new factory classmethod, `from_zaaktype_configs`, next to the existing `from_catalogus_configs`, that basically does the same thing, except return `CatalogusConfig.objects.empty()` for the catalogus configs.

Perhaps I am missing something, but I don't think the export logic actually depends on catalogus config exports being present (beyond the constructor method, where you use the catalogus configs to limit which zaaktype configs to select).

2024-12-03 11:29 UTC, swrichards commented on src/open_inwoner/openzaak/import_export.py
> +class ZGWConfigExport:
So we'd get something like:

```python
@@ -210,6 +212,36 @@ class CatalogusConfigExport:
             zaak_resultaat_type_configs=zaak_resultaat_type_configs,
         )
 
+    @classmethod
+    def from_zaaktype_configs(cls, zaak_type_configs: QuerySet) -> Self:
+        if not isinstance(zaak_type_configs, QuerySet):
+            raise TypeError(
+                f"`zaaktype_configs` is not a QuerySet, but a {type(zaak_type_configs)}"
+            )
+
+        if zaak_type_configs.model != ZaakTypeConfig:
+            raise ValueError(
+                f"`zaaktype_configs` is of type {zaak_type_configs.model}, not ZaakTypeConfig"
+            )
+
+        informatie_object_types = ZaakTypeInformatieObjectTypeConfig.objects.filter(
+            zaaktype_config__in=zaak_type_configs
+        )
+        zaak_status_type_configs = ZaakTypeStatusTypeConfig.objects.filter(
+            zaaktype_config__in=zaak_type_configs
+        )
+        zaak_resultaat_type_configs = ZaakTypeResultaatTypeConfig.objects.filter(
+            zaaktype_config__in=zaak_type_configs
+        )
+
+        return cls(
+            catalogus_configs=CatalogusConfig.objects.none(),
+            zaak_type_configs=zaak_type_configs,
+            zaak_informatie_object_type_configs=informatie_object_types,
+            zaak_status_type_configs=zaak_status_type_configs,
+            zaak_resultaat_type_configs=zaak_resultaat_type_configs,
+        )
+
```

2024-12-03 15:20 UTC, pi-sigma commented on src/open_inwoner/openzaak/import_export.py
> +class ZGWConfigExport:
Nice pattern, except for `from_zaaktype_configs` we need to return `objects.none()` for the other ZGW objects as well.

2024-12-04 09:57 UTC, swrichards approved these changes

2024-12-04 09:57 UTC, swrichards commented on src/open_inwoner/openzaak/admin.py
> +from open_inwoner.openzaak.import_export import CatalogusConfigImport, ZGWConfigExport
I guess we could propagate the rename to the import container as well:

```suggestion
from open_inwoner.openzaak.import_export import ZGWConfigImport, ZGWConfigExport
```

2024-12-04 09:57 UTC, swrichards commented on src/open_inwoner/openzaak/admin.py
> +    def process_file_view(self, request):
The only thing that springs to mind is whether to do this as a mixin, given that there's non trivial logic here. But I would say we can add that to the technical debt list (because I think we might also want to add a Celery option given how long these imports take, but it shouldn't delay the current PR and patch release).

2024-12-04 10:03 UTC, merged

2024-12-04 10:05 UTC, pi-sigma commented on src/open_inwoner/openzaak/admin.py
> +    def process_file_view(self, request):
Noted, I'll create a Taiga issue for this.