[#2940] Add OpenKlant2 configuration model
maykinmedia/open-inwoner pull request #1529
Opened 2024-12-16 16:11 UTC by pi-sigma

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2940

2024-12-17 07:38 UTC, swrichards commented on src/open_inwoner/accounts/views/signals.py
> +    if openklant2_config := OpenKlant2Config.get_solo():
@pi-sigma I think this is a reason not to use a singleton for the OK2 config model, because this will never be null, it will always return something.

I wonder if it isn't preferable to not make it a singleton, and instead actually make some of the fields (such as the service and mijn vragen actor) required, so that we know _if_ we have a config, it'll be valid.

2024-12-17 07:39 UTC, swrichards commented on src/open_inwoner/openklant/tests/test_openklant2_service.py
> +        )
Curious: this was required?

2024-12-17 08:54 UTC, pi-sigma commented on src/open_inwoner/openklant/tests/test_openklant2_service.py
> +        )
The `zgw_service` needs a certificate, can't get away with a string

2024-12-17 08:56 UTC, pi-sigma commented on src/open_inwoner/accounts/views/signals.py
> +    if openklant2_config := OpenKlant2Config.get_solo():
Fair point, will get back to this once I have the tests passing.

2024-12-18 11:32 UTC, swrichards requested changes
Looks good, just a few minor points which might require attention (especially the singleton issue).

2024-12-18 11:32 UTC, swrichards commented on src/open_inwoner/openklant/models.py
> +    zgw_service = models.OneToOneField(
I think `service` would be slightly preferable here, because (I believe) the `zgw` part is apparently more of a legacy name, we use the `Service` for all kinds of backend.

2024-12-18 11:32 UTC, swrichards commented on src/open_inwoner/openklant/models.py
> +        limit_choices_to={"api_type": APITypes.kc},
I'd like to remove this constraint for now: as above, I believe the api types are also somewhat redundant, and there's no specific constant to distinguish openklant2 for klanten/contactmomenten.

2024-12-18 11:32 UTC, swrichards commented on src/open_inwoner/openklant/tests/test_openklant2_service.py
> +        zgw_service, _ = Service.objects.update_or_create(
Curious: why not just use `ServiceFactory` here and throughout? We do that elsewhere in tests when we need services.

2024-12-18 11:32 UTC, swrichards commented on src/open_inwoner/openzaak/tests/test_case_detail.py
> +        )
We could consider also adding an `OpenKlant2ConfigFactory` given that a lot of the fields are basically static (it could even then use a SubFactory to create the service by default if no specific service is needed, possibly with a default api root).

2024-12-18 11:32 UTC, swrichards commented on src/open_inwoner/openklant/services.py
> +        self.config = config or OpenKlant2Config.get_solo()
As per an earlier comment, doesn't `get_solo` always return a model, i.e. it creates it if not defined, or does this return `None` if not defined?

The reason is that the check on `l.827` will then never fail, but we might not have the fields we need.

2024-12-18 11:32 UTC, swrichards commented on src/open_inwoner/openklant/models.py
> +        return qs.select_related("service_config")
Should this be:

```suggestion
        return qs.select_related("zgw_service")
```

2024-12-18 11:32 UTC, swrichards commented on src/open_inwoner/openklant/models.py
> +        verbose_name = _("Open Klant configuration")
```suggestion
        verbose_name = _("OpenKlant2 configuration")
```

2024-12-18 12:11 UTC, pi-sigma commented on src/open_inwoner/openklant/services.py
> +        self.config = config or OpenKlant2Config.get_solo()
You're right, that's from our earlier implementation. I'm inclined to check for `config.service` and raise `ImproperlyConfigured` if it's not there (`get_solo` will return an object without service). What do you think?

2024-12-18 12:29 UTC, swrichards commented on src/open_inwoner/openklant/services.py
> +        self.config = config or OpenKlant2Config.get_solo()
I am a bit concerned that we would need a lot of ad-hoc checks all over the place for the specific fields we expect in a specific context. For instance, the mijn vragen settings are in fact required to be able to use the "mijn vragen" page with OK2. It is in a way easier to just say "OK2 is configured or not configured", but if it is configured, the database has enforced the presence of the fields we care about.

That being said, that would in this case mean you cannot configure OK2 without knowing in advance (particularly) the Mijn Vragen Actor, which is annoying. So perhaps we can't avoid doing field specific checks.

TLDR: I am not sure, but let's then check the service for now as you suggest. I suspect what we'll have to do later is to make the "interne taak" part of the question/answer bit conditional upon actually have a mijn vragen actor.

2024-12-18 14:08 UTC, swrichards requested changes

2024-12-18 14:08 UTC, swrichards commented on src/open_inwoner/openzaak/tests/test_cases.py
> +        user_logged_in.disconnect(update_user_from_klant_on_login)
Are these disconnects still needed now that we properly check the errors everywhere?

2024-12-18 14:08 UTC, swrichards commented on src/open_inwoner/openklant/tests/factories.py
> +    service: Service
This can be a `factory.SubFactory(ServiceFactory, api_root=KLANTEN_ROOT_VCR, api_type=...)`, then you don't have to repeat this in your invocations.

2024-12-18 14:08 UTC, swrichards commented on src/open_inwoner/openklant/tests/data.py
> +KLANTEN_ROOT_VCR = "http://localhost:8338/klantinteracties/api/v1"
I'd like to make this `OPEN_KLANT2_ROOT` because `KLANTEN` is just a bit too close to the eSuite "klanten" to cause confusion.

2024-12-18 14:08 UTC, swrichards commented on src/open_inwoner/accounts/tests/test_oidc_views.py
> +        signals.user_logged_in.disconnect(update_user_from_klant_on_login)
Same question as below: are these disconnects still needed?

2024-12-18 14:12 UTC, swrichards commented on src/open_inwoner/openzaak/tests/test_case_detail.py
> -                    MockOpenKlant2Service().retrieve_question()[0],
Does this mean we're no longer testing questions retrieved by OK2?

2024-12-18 15:16 UTC, pi-sigma commented on src/open_inwoner/openzaak/tests/test_case_detail.py
> -                    MockOpenKlant2Service().retrieve_question()[0],
Removed this when debugging the tests, but forgot to add back in.

2024-12-18 15:30 UTC, swrichards commented on src/eherkenning/tests/test_mock_views.py
> +
Just out of idle curiosity: why was this one the only require disconnect?

2024-12-18 15:30 UTC, swrichards approved these changes

2024-12-18 15:34 UTC, pi-sigma commented on src/eherkenning/tests/test_mock_views.py
> +
Argh, missed this one, sorry!

2024-12-18 17:03 UTC, swrichards approved these changes

2024-12-18 17:07 UTC, alextreme approved these changes

2024-12-18 17:08 UTC, merged