[#296] Feature/openforms integration
maykinmedia/open-inwoner pull request #224
Opened 2022-05-17 11:07 UTC by vaszig

This PR cannot be merged until the reported issue concerning Open Forms and failing fonts is handled 
- https://github.com/open-formulieren/open-forms/issues/1615

2022-05-20 13:21 UTC, annashamray commented
I have zero knowledge of open forms, so I'll add also other reviewers

2022-05-23 12:12 UTC, alextreme commented
This likely will clash with the CSP headers that we'll introduce with PR 228 (as it will mean that we can't integrate external entities easily). Lets wait and revisit this after that's done, the OF integration isn't urgent.

2022-05-23 14:05 UTC, JostCrow requested changes

2022-05-23 14:05 UTC, JostCrow commented on src/open_inwoner/templates/pages/product/detail.html
> +{% if product.form_snippet %}
Adding the form snippet here only adds it for desktop. So there will be no openforms integration for mobile.

2022-05-23 14:05 UTC, JostCrow commented on src/open_inwoner/templates/pages/product/detail.html
> +            {{ product.form_snippet|safe }}
Was there no other way of rendering this without using the safe?
Also, this will not load with the CSP headers enabled.

2022-06-27 13:51 UTC, JostCrow commented
@vaszig Can you update this? Since it should be merged in OpenForms.

2022-08-29 07:28 UTC, joeribekker commented
This was fixed and merged in OF in July 5

2022-10-19 12:09 UTC, alextreme commented
Resolved by Joeri via #311 while making use of Vasileios's approach, I believe this PR can be closed

2022-11-28 13:49 UTC, svenvandescheur commented on src/open_inwoner/js/components/openforms/index.js
> +    this.openforms.classList.add('openforms--show')
A better way of showing/hiding things might be by setting aria-hidden as it will also remove thing for screen readers.

2022-11-28 13:49 UTC, svenvandescheur commented on src/open_inwoner/scss/components/OpenForms/OpenForms.scss
> +  &--show {
See remarkt about aria-hidden, we can target it here by that attribute as well.

2022-11-29 15:22 UTC, closed without merging