[#618] Feature/autofocus in mobile questionnaire
maykinmedia/open-inwoner pull request #242
Opened 2022-05-24 10:49 UTC by vaszig

2022-05-24 17:31 UTC, alextreme commented
Leaving for Jorik to review, I'm not in a rush to get this in

2022-05-25 09:48 UTC, JostCrow requested changes

2022-05-25 09:48 UTC, JostCrow commented on src/open_inwoner/js/components/questionnaire/index.js
> +const stepIndicators = document.querySelectorAll(
There should only be one active item. So I would say that we should not use querySelectorAll.
Also by selecting multiple (if there are) you will scroll to the first, than the second, than the third.

2022-05-30 12:40 UTC, alextreme commented
Merging and double-checking on the testenv

2022-05-30 12:40 UTC, merged