[#1051-3] Feature/Haalcentraal BRP data view
maykinmedia/open-inwoner pull request #429
Opened 2023-01-17 11:50 UTC by vaszig

2023-01-17 16:44 UTC, alextreme commented on src/open_inwoner/accounts/views/profile.py
> +        fetched_data = fetch_brb_data(user, brp_version)
fetch_brp_data, not brb :)

2023-01-17 16:45 UTC, alextreme commented on src/open_inwoner/haalcentraal/signals.py
> -def fetch_data(instance, brp_version):
Good to move this out of signals.py

2023-01-17 16:53 UTC, alextreme requested changes
Glad to see this taking shape, nice work!

In your fetch_brp_data utils function please also log to timelinelogger (utils.user_action) that a User (object) requests the BRP data. This to provide visibility on when external calls have been performed.

2023-01-18 08:41 UTC, Bartvaderkin requested changes

2023-01-18 08:41 UTC, Bartvaderkin commented on src/open_inwoner/accounts/views/profile.py
> +            fetched_data = glom(fetched_data, "personen")[0]
You don't need to glom if it is only one level deep `fetched_data["personen"][0]`

2023-01-18 08:41 UTC, Bartvaderkin commented on src/open_inwoner/haalcentraal/utils.py
> +    logger.warning(brp_version)
This warning feels a bit lost.

2023-01-18 08:41 UTC, Bartvaderkin commented on src/open_inwoner/accounts/views/profile.py
> +            else "geslachtsaanduiding",
Please put parenthesis around inline if/else so it black's for better visibility.

2023-01-18 08:41 UTC, Bartvaderkin commented on src/open_inwoner/accounts/views/profile.py
> +                my_data[field] = None
`glom()` has a `default` parameter so you don't need the try/except.

2023-01-18 10:29 UTC, Bartvaderkin approved these changes

2023-01-18 14:42 UTC, alextreme approved these changes

2023-01-18 14:42 UTC, merged