[#1156] Feature/add email and phonenumber to map and location cards
maykinmedia/open-inwoner pull request #495
Opened 2023-02-23 09:41 UTC by vaszig

2023-02-23 10:59 UTC, jiromaykin commented on src/open_inwoner/scss/components/Map/_Map.scss
> +  flex-wrap: wrap;
You would need to add this to it: 
`flex-direction: column;`
Everything else looks good! 
Explanation: The leaflet-map address etc. will look weird if locations have long names + while still breaking neatly on a hyphen (the location details would be **next** to each other in stead of on top of each other, making it difficult to read without a margin.):
![image](https://user-images.githubusercontent.com/118177951/220887731-62afbd5d-41ef-43fb-bcc1-a6a58304d5b6.png)

2023-02-23 11:21 UTC, Bartvaderkin requested changes
In the map bubble, I think we'd want each property on it's own line like on the detail page? It is unusual to concatenate them together.

2023-02-23 11:21 UTC, Bartvaderkin commented on src/open_inwoner/js/components/map/index.js
> +        </div>
These values aren't html escaped.

2023-03-01 15:47 UTC, vaszig commented
I had to specify the version of `babel-loader` package since it was updated automatically to the latest version (not compatible with the CI node version).


![image](https://user-images.githubusercontent.com/63058071/222189856-a1b3840a-00fe-488e-b121-4bcaaa97264e.png)

2023-03-02 13:52 UTC, Bartvaderkin approved these changes

2023-03-03 09:09 UTC, jiromaykin commented
> I had to specify the version of `babel-loader` package since it was updated automatically to the latest version (not compatible with the CI node version).

Which CI node-version are we using? Should we keep NodeJS to the latest version or not? I don't know much about this yet :-)  so I wonder how we will keep track of CI node and change Babel-parser to latest again?

2023-03-03 09:13 UTC, jiromaykin approved these changes
Looks all good to me now ,when viewed in browser.

2023-03-03 09:14 UTC, vaszig commented
> > I had to specify the version of `babel-loader` package since it was updated automatically to the latest version (not compatible with the CI node version).
> 
> Which CI node-version are we using? Should we keep NodeJS to the latest version or not? I don't know much about this yet :-) so I wonder how we will keep track of CI node and change Babel-parser to latest again?

In CI we are using node 12.22.12, which is not compatible with the latest version of babel-loader. I am not an expert concerning all these, but I know that it's better to pin a problematic package instead of upgrading node (which may cause problems to several packages then).

2023-03-03 10:39 UTC, merged