[#1128] Add icon to cases document upload button
maykinmedia/open-inwoner pull request #517
Opened 2023-03-03 15:40 UTC by vaszig

2023-03-06 09:42 UTC, vaszig commented
Only the last commit is for review.

2023-03-06 11:38 UTC, Bartvaderkin approved these changes

2023-03-06 11:49 UTC, jiromaykin commented on src/open_inwoner/templates/pages/cases/status.html
> +                        {% button href=case.external_upload_url text=_("Document toevoegen") primary=True icon="open_in_new" icon_position="after" %}
For accessibility purposes the icon here needs an aria-label with the translatable text "Opens new window" - but it's also OK to put the aria-label in the Anchor link if that's easier.

2023-03-06 15:00 UTC, jiromaykin requested changes
So here is an official request :-) with the same accessibility issue as stated: 
"For accessibility purposes the icon here needs an aria-label with the translatable text-string "Opens new window" - but it's also OK to put the aria-label in the Anchor link if that's easier."

2023-03-06 15:45 UTC, vaszig commented
> So here is an official request :-) with the same accessibility issue as stated: "For accessibility purposes the icon here needs an aria-label with the translatable text-string "Opens new window" - but it's also OK to put the aria-label in the Anchor link if that's easier."

@jiromaykin done. Added the aria-label and rebased in order to have a cleaner branch as well.

2023-03-06 16:11 UTC, jiromaykin commented
A 'title' attribute actually is not accessible for screen-readers (but yes, it is still necessary for other users, so keep the title like you have now);
but it still needs an actual _**aria-label** attribute_; 
in HTML, it looks like this:
`aria-label="Opens new window"`
(but with translation)

Maybe I am saying too much here, but just a little more info:
- Do not use the attribute with the similar name "aria-labelledby" here because that's only for ID's.
- If you cannot add the aria-label, another trick to make this accessible is by adding an invisible Span element that contains the text "Opens new window" and **[is made invisible with CSS](https://webaim.org/techniques/css/invisiblecontent/)** by adding a new css class to the project, like 'visuallyhidden' or 'sr-only' and set its properties something like this:

`.sr-only {
position:absolute;
left:-10000px;
top:auto;
width:1px;
height:1px;
overflow:hidden;
}`

I hope this is clear and helpful.

2023-03-07 07:33 UTC, vaszig commented
> A 'title' attribute actually is not accessible for screen-readers (but yes, it is still necessary for other users, so keep the title like you have now); but it still needs an actual _**aria-label** attribute_; in HTML, it looks like this: `aria-label="Opens new window"` (but with translation)
> 
> Maybe I am saying too much here, but just a little more info:
> 
>     * Do not use the attribute with the similar name "aria-labelledby" here because that's only for ID's.
> 
>     * If you cannot add the aria-label, another trick to make this accessible is by adding an invisible Span element that contains the text "Opens new window" and **[is made invisible with CSS](https://webaim.org/techniques/css/invisiblecontent/)** by adding a new css class to the project, like 'visuallyhidden' or 'sr-only' and set its properties something like this:
> 
> 
> `.sr-only { position:absolute; left:-10000px; top:auto; width:1px; height:1px; overflow:hidden; }`
> 
> I hope this is clear and helpful.

By defining the variable `title` of the template tag (which, if defined, adds an aria-label attribute according to the template) I wanted to add an aria-label attribute. Maybe I don't get something here but with my changes there is an aria-label attribute:

![image](https://user-images.githubusercontent.com/63058071/223351895-ac986f61-5337-46f9-94ea-69f216380337.png)

2023-03-07 09:02 UTC, jiromaykin commented
> By defining the variable `title` of the template tag (which, if defined, adds an aria-label attribute according to the template)

Oh wow, I did not know that - sorry - i will approve this :-)

2023-03-07 09:03 UTC, jiromaykin approved these changes

2023-03-07 09:05 UTC, vaszig commented
> Oh wow, I did not know that - sorry - i will approve this :-)

No problem..the template tags are a bit complicated. Thanks for the helpful comments though!

2023-03-08 11:43 UTC, merged