:lipstick: [#1064] Remove large space in footer and products on mobile
maykinmedia/open-inwoner pull request #525
Opened 2023-03-10 13:32 UTC by jiromaykin

For mobile, see: https://taiga.maykinmedia.nl/project/open-inwoner/task/1164

2023-03-13 14:55 UTC, Bartvaderkin approved these changes

2023-03-13 15:19 UTC, vaszig requested changes
![image](https://user-images.githubusercontent.com/63058071/224745480-f32c2306-3cfa-4257-940f-c4f09cdb1b86.png)

2023-03-13 16:41 UTC, jiromaykin commented on src/open_inwoner/scss/components/Footer/Footer.scss
> +    display: grid;
@vaszig  Which page are you showing in your comment (the Footer__logo shouldn't be everywhere, only in footer?)

2023-03-14 07:45 UTC, vaszig commented on src/open_inwoner/scss/components/Footer/Footer.scss
> +    display: grid;
It is the home page. You can add a footer logo in order to reproduce it.

2023-03-14 11:52 UTC, vaszig approved these changes

2023-03-15 10:17 UTC, merged