:art: [#1021] Make entire Product card clickable
maykinmedia/open-inwoner pull request #554
Opened 2023-03-23 15:03 UTC by jiromaykin

New clean branch for [old issue](https://github.com/maykinmedia/open-inwoner/pull/457).
Templates will need some more simplification, because currently they are not very maintainable.

2023-03-23 16:26 UTC, jiromaykin commented
The famous clickable templates problem... I probably made some terrible choices here; feel free to suggest improvements.

2023-03-24 08:14 UTC, Bartvaderkin requested changes
:+1: for saner tags.

2023-03-24 08:14 UTC, Bartvaderkin commented on src/open_inwoner/components/templates/components/Card/ProductCard.html
> +            {% endif %}
The indentation is a bit off here and makes it difficult to see the html/template tag nesting.

2023-03-24 08:14 UTC, Bartvaderkin commented on src/open_inwoner/components/templates/components/Card/RenderCard.html
> +            {% if compact %}
You can do `and` in if-tags: `{% if title and compact %}`

2023-03-24 08:14 UTC, Bartvaderkin commented on src/open_inwoner/templates/pages/cases/list.html
> +                            <a href="/accounts/cases/{{ case.uuid }}/status/" class="case-list">
Don't build urls as strings, use the `{% url %}` tag to reverse it from the router: https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#url

I think it'd be like `{% url 'accounts:case_status' object_id=case.uuid %}`

2023-03-24 08:44 UTC, vaszig requested changes
One remark..don't we want the plan cards on home page to be clickable as well?I know this has to do with the product cards, but I am mentioning this because I saw we have updated plan cards as well (plan-list view).

2023-03-24 08:44 UTC, vaszig commented on src/open_inwoner/components/templates/components/Card/RenderCard.html
> +            <p class="h4">
Indentation here can be fixed as well.

2023-03-24 08:44 UTC, vaszig commented on src/open_inwoner/components/templates/components/Card/DescriptionCard.html
> +{% load card_tags icon_tags link_tags button_tags i18n grid_tags thumbnail %}
`button_tags` template tag is not used anywhere, can be removed.

2023-03-27 10:07 UTC, Bartvaderkin commented on src/open_inwoner/components/templates/components/Card/RenderCard.html
> +            {% if compact %}
:hear_no_evil: :see_no_evil:

2023-03-27 10:46 UTC, jiromaykin commented
Overview of URL's for testing and checking:
## Overview of cards on frontend:
-Home/Themas theme-cards (RenderCard), with or without image, no description, no arrow:
http://127.0.0.1:8000/themas/
-Product Cards with title, description and arrows, no selected image:
http://127.0.0.1:8000/themas/opvoeding-en-gezin/
-small SUB CategoryCard without description or image, just a title:
http://127.0.0.1:8000/themas/zorg-en-ondersteuning/
-Cards from a Theme hierarchy with lots of arrows linking to products (should only become clickable if there are no links inside):
https://open-inwoner-test.maykin.nl/themas/gezond-blijven/
-larger DescriptionCard (inside RenderCard) with image on the left + description:
http://127.0.0.1:8000/themas/zorg-en-ondersteuning/ (huiselijk geweld card)
-Inloggen/login card, (with tinted cards inside):
http://127.0.0.1:8000/accounts/login/
-Register page, (with tinted cards inside):
http://127.0.0.1:8000/accounts/register/
-after oggign in: Theme cards on Home page:
http://127.0.0.1:8000/
-Samenwerken overview cards (after logging in, normal user), RenderCard with date and arrow
http://127.0.0.1:8000/plans/
-Table-like RenderCard in Mijn Aanvragen/Cases (after logging in, normal user) with date and status and arrow
http://127.0.0.1:8000/accounts/cases/open/
-Location card with text only, no links (scroll to bottom of page)
http://127.0.0.1:8000/themas/opvoeding-en-gezin/products/ditiseenredelijklangetitelvan-een-product-en-levert-problemen-op-in-anchor-menu/

2023-03-27 13:32 UTC, jiromaykin commented
> One remark..don't we want the plan cards on home page to be clickable as well?

Good idea - I will make a new PR for the Home page cards, because those are  slightly different and will have the same problem (surrounding anchor linkswill break if there are links inside the content).

2023-03-28 10:56 UTC, jiromaykin commented
I've made many of the templates on pages very static now; only RenderCard is still very dynamic - hopefully this makes things bit easier for the future already.

2023-03-29 07:17 UTC, Bartvaderkin approved these changes

2023-04-02 19:28 UTC, merged