[#1328] Add checkboxes for cases,plans,messages notifications to Profile page
maykinmedia/open-inwoner pull request #579
Opened 2023-04-12 14:29 UTC by vaszig

2023-04-14 07:34 UTC, Bartvaderkin approved these changes
Neat!

2023-04-14 07:34 UTC, Bartvaderkin commented on src/open_inwoner/accounts/urls.py
> +    path("notifications/", MyNotificationsView.as_view(), name="my_notifications"),
I just like to note this 'My' naming pattern is awful but I'll accept it as at least it keeps the pattern.

2023-04-14 07:34 UTC, Bartvaderkin commented on src/open_inwoner/accounts/tests/test_notify_about_messages.py
> +
Not an issue but notably different whitespace compared to the others :wink:

2023-04-14 16:43 UTC, alextreme commented on src/open_inwoner/templates/pages/profile/notifications.html
> +    {% trans "Kies voor welke categorie je notificaties wil ontvangen" %}
Lets go for 'meldingen' in the Dutch labels

2023-04-17 08:39 UTC, alextreme requested changes
Ensure dutch labels use 'Communicatievoorkeuren' instead of 'mijn notificaties'.

We discussed last week to use 'meldingen' however this term is overloaded.

2023-04-18 08:35 UTC, jiromaykin approved these changes

2023-04-18 11:11 UTC, alextreme approved these changes

2023-04-18 11:12 UTC, merged