[#1405] Cleanup 'show_xyz' booleans from siteconfiguration
maykinmedia/open-inwoner pull request #609
Opened 2023-05-08 10:39 UTC by vaszig

2023-05-09 08:11 UTC, alextreme commented
Did a quick check with Vasileios and looks good imho

2023-05-11 07:49 UTC, Bartvaderkin requested changes

2023-05-11 07:49 UTC, Bartvaderkin commented on src/open_inwoner/plans/views.py
> +            profile_namespace = resolve(reverse("profile:action_list")).namespace
This reverse will throw an error if the profile app is not active.

2023-05-11 10:15 UTC, Bartvaderkin approved these changes

2023-05-11 10:15 UTC, merged