[#1442] Fix django-admin-index fixture
maykinmedia/open-inwoner pull request #615
Opened 2023-05-11 13:09 UTC by vaszig

2023-05-11 15:03 UTC, Bartvaderkin requested changes
The change in formatting makes it hard to see actual changes in the diff.
 
Do you generate this with the `generate_admin_index_fixture.sh` script from the bin folder? 

If I look at the GIT history I see some other changes that look a bit suspicious.

2023-05-12 06:53 UTC, vaszig commented
> The change in formatting makes it hard to see actual changes in the diff.
> 
> Did you generate this with the `generate_admin_index_fixture.sh` script from the bin folder?
> 
> If I look at the GIT history I see some other changes that look a bit suspicious.

@Bartvaderkin  I did this in this way but black formatted the json file, so I reverted it and it works as expected

2023-05-12 07:17 UTC, Bartvaderkin commented
@vaszig I don't think you're supposed to black json :D

Check what your using as githook or script so it filters on python files.

2023-05-12 07:51 UTC, Bartvaderkin approved these changes

2023-05-12 13:47 UTC, merged