[#1439] Add htmx to cases
maykinmedia/open-inwoner pull request #621
Opened 2023-05-16 14:35 UTC by vaszig

2023-06-13 05:46 UTC, vaszig commented
@jiromaykin FYI if you want to freeze the spinner and review it properly you can add a breakpoint to the cases (cms/cases/views/cases.py -> `InnerOpenCaseListView.get_cases()`) . Let me know if you need any help.

2023-06-13 07:37 UTC, Bartvaderkin commented on src/open_inwoner/cms/cases/views/mixins.py
> +            return TemplateResponse(self.request, "pages/cases/403.html")
neat!

2023-06-13 09:13 UTC, Bartvaderkin requested changes
Htmx stuff looks pretty good.

One thing that bothers me is the javascript components don't chain from the node that is found by the selector, but use global selectors to grab the various sub-elements and attach event handlers. 

This is not accurate and could give memory leaks because if the selector matches the new html fragment the component could still find and (duplicated) attach to elements outside of the fragment. Eg: multiple instantiations of the component code could connect to the same elements.

2023-06-13 10:13 UTC, jiromaykin commented
> ...FYI if you want to freeze the spinner and review it properly you can add a breakpoint to the cases[...].

Thanks! I am excited to test this!

2023-06-13 12:51 UTC, jiromaykin requested changes
Maybe it's just me, but when the list view has loaded (any list open/closed/Lopende) - I still see the spinner at the bottom after data has loaded (spinner should disappear here after loading is done),
When this happens it seems like javascript is becoming unresponsive because I cannot open the desktopmenu navigation anymore from this page.
 
<img width="1014" alt="listview-aanvraag" src="https://github.com/maykinmedia/open-inwoner/assets/118177951/f109f76b-e460-4fb2-a043-ab5f82f6de5f">

2023-06-13 13:58 UTC, vaszig commented
> > Maybe it's just me, but when the list view has loaded (any list open/closed/Lopende) - I still see the spinner at the bottom after data has loaded
> 
> Additionally: the main-navigation still works if I log in as a DigiD user - but it still has the spinner still visible after data has loaded.

@jiromaykin have you reloaded-rebuilt js in your local machine?It seems weird because I don't seem to have a problem.

2023-06-13 14:35 UTC, jiromaykin requested changes

2023-06-13 14:35 UTC, jiromaykin commented on src/open_inwoner/scss/components/Spinner/Spinner.scss
> +    animation: rotate 2.5s linear infinite;
I feel this is just a tiny bit too slow, even if you have to wait long - 1.5 seconds would feel better.
All else looking good!

2023-06-13 14:36 UTC, jiromaykin commented
> 
> [...] have you reloaded-rebuilt js in your local machine?It seems weird because I don't seem to have a problem.

Sorry @vaszig - I thought the Watch function did a clean rebuild. It's working correctly after one build.

2023-06-14 09:57 UTC, Bartvaderkin approved these changes
I still see a lot of global selectors (eg: ID's, `getElementById(x)` or `querySelector("#x")` in the components. 

As everything works I'll approve to land this larger PR and added Taiga issue 1544 (and earlier 1511) to clean this up.

2023-06-14 09:57 UTC, Bartvaderkin commented on src/open_inwoner/js/components/upload-document/show-file-info.js
> +    const submit_upload = documentUpload.querySelector('#submit_upload')
This still uses ID's, eg: global selectors. I'm not sure what browsers do with duplicate ID's even if you'd `querySelector from a one of their ancestor elements, or how this works with closest. 

The point of this is making sure that when hydrating one fragment we're not accidentally select elements elsewhere in the page. 

In this case I'll not block on this as there won't be multiple of this element.

2023-06-14 10:14 UTC, merged