[#1456] Added 'infix' (tussenvoegsel) to User model
maykinmedia/open-inwoner pull request #633
Opened 2023-05-23 12:57 UTC by Bartvaderkin

PR for CI

2023-05-25 13:42 UTC, vaszig requested changes
Looks good! Let's add the infix field to the `profile/edit.html` as well, because we render the fields manually.

2023-05-25 13:42 UTC, vaszig commented on src/open_inwoner/haalcentraal/tests/test_signal.py
> +        user.refresh_from_db()
Thanks for the updated part!

2023-05-26 07:07 UTC, Bartvaderkin commented
> Looks good! Let's add the infix field to the `profile/edit.html` as well, because we render the fields manually.

Thanks, weird how I missed that. I appended a commit for it.

2023-05-26 07:11 UTC, vaszig approved these changes

2023-05-30 12:39 UTC, merged