[#1509] fix template 'form.html'
maykinmedia/open-inwoner pull request #647
Opened 2023-06-05 10:32 UTC by pi-sigma

Removed sidebar and form overview from the form template so that they are no longer displayed once a form has been started.

Taiga: #1509

2023-06-07 09:29 UTC, vaszig requested changes
Let's remove the anchors from the view (`ProductFormView`) since we don't use the sidebar anymore. It shows errors when Gumshoe tries to access them.

![image](https://github.com/maykinmedia/open-inwoner/assets/63058071/cb4090a0-ba46-4ca1-9a1c-30212d3712ea)

2023-06-08 13:35 UTC, pi-sigma commented
I set up integration with openforms locally and the solution works:

![oi-of-local](https://github.com/maykinmedia/open-inwoner/assets/89185369/0ccf5988-8107-476c-9d2a-97b89b2d3896)

On the other hand, in the test environment:

![oi-of-test](https://github.com/maykinmedia/open-inwoner/assets/89185369/0c706cc2-3adc-429f-8d78-5cdb69bf1215)

@alextreme Does the test environment already include this patch?

2023-06-09 17:55 UTC, alextreme commented
@pi-sigma no, this PR is not merged yet so it won't be on the testenvironment.

After you make your changes hit the 're-review' icon next to your reviewers name

2023-06-13 05:44 UTC, vaszig approved these changes

2023-06-13 09:48 UTC, merged