[#1503] add name validation to user model
maykinmedia/open-inwoner pull request #656
Opened 2023-06-07 10:22 UTC by pi-sigma

2023-06-07 10:59 UTC, pi-sigma commented
Another point: while the code prevents execution of HTML, it doesn't address the question why the HTML isn't automatically escaped by Django, as it normally is.

2023-06-08 12:34 UTC, vaszig commented
> @vaszig I thought about removing `validate_charfield_entry` entirely and replacing it with `NameValidator`. On the other hand, the function is used in various places (see the failing tests which I overlooked). Secondly, `validate_charfield_entry` does reject / so prevents the execution of JavaScript. I still prefer the approach with a class-based RegexValidator since it is more idiomatic (?), but I'd like to hear what you think before I make any further changes.

I think I would go for the class validator since we need to avoid some additional characters. But each solution needs the tests to be modified, so we don't avoid this. @Bartvaderkin can you tell us your opinion please?

2023-06-13 06:24 UTC, vaszig reviewed
A small remark concerning the name of the validator..

I see that we are now using the `NameValidator` class for several fields in the User model and the name of the validator is not really representative. Maybe something that declares it's for the charfields?

Concerning escaping characters with js, @Bartvaderkin should review this as well.

2023-06-13 06:24 UTC, vaszig commented on src/open_inwoner/js/components/autocomplete/index.js
> +  console.log('node', node)
Do we need them?

2023-06-13 06:46 UTC, pi-sigma commented
@Bartvaderkin HTML escape in the dropdown is fixed. However, I'm not quite sure whether this was simply an oversight on our part or whether escaping is the responsibility of the library we're using for autocompletion (JavaScript type-ahead widgets are a known source of XSS-vulnarability in Django but I'm not sure about the present case).

2023-06-13 07:23 UTC, Bartvaderkin requested changes

2023-06-14 08:04 UTC, Bartvaderkin requested changes

2023-06-14 08:04 UTC, Bartvaderkin commented on src/open_inwoner/js/components/autocomplete/index.js
> +    document.getElementById('autocomplete-choices').textContent
See the note in the template.

2023-06-14 14:33 UTC, Bartvaderkin approved these changes

2023-06-15 07:11 UTC, vaszig approved these changes

2023-06-15 07:26 UTC, merged