:zap:  [#1485] Hide extra expiration warning before DigiD session ends
maykinmedia/open-inwoner pull request #660
Opened 2023-06-08 09:51 UTC by jiromaykin

https://taiga.maykinmedia.nl/project/open-inwoner/issue/1485

**_Note: can only be reproduced when logging in as a DigiD user!
and only works when clicking the buttons - not by clicking outside modal_** so clicking outside the buttons needs to be removed.

Explanation: clicking outside the modal, closes it, but also bypasses any necessary Confirm/Submit.

1. There is one warning that needs to stay (14 minutes in - but it has to disappear after 15 minutes, which it doesn't right now):
<img width="1406" alt="Screenshot 2023-06-08 at 11 50 26" src="https://github.com/maykinmedia/open-inwoner/assets/118177951/cc31bc7f-f97a-45ec-b857-ef4cd8333799">

2. This one needs to stay - it appears after 15 minutes of inactivity - if this one is clicked, it should redirect to the LOGIN page, not to the Home page:
<img width="1473" alt="Screenshot 2023-06-08 at 11 47 02" src="https://github.com/maykinmedia/open-inwoner/assets/118177951/0a6fa760-eba5-4a75-a6ea-9576e1538534">

But if you keep on having inactivity after more than 15 minutes the first modal needs to be invisible (the first one pops up after clicking the second one again, should not happen).

2023-09-04 07:43 UTC, jiromaykin commented
@alextreme @Bartvaderkin Met deze heb ik erg lang geworsteld en om onbegrijpelijke redenen lijkt dit nu wel te werken met gewenste effect: dus 1) de redirect voert naar de inlog-pagina i.p.v. home, en 2) de Warning modal lijkt niet meer te blijven hangen wanneer de Expiration modal verschijnt - dubbelchecken nodig.

2023-09-04 09:37 UTC, Bartvaderkin commented on src/open_inwoner/js/components/session/index.js
> +    }, (this.expiryAge + 1) * 1000)
(we discussed use of bind() and arrow functions in person)

2023-09-05 10:32 UTC, Bartvaderkin reviewed
@jiromaykin Note both of the changed parts do the same thing in two ways:

- the first one uses an arrow function and no bind() (and it works because the arrow function preserves `this` so we can call the method on it).
- the second one just bind()'s without arrow function  (and it works because we explicitly bind `this` to the function reference so it has an explicit `this`).

2023-09-05 10:46 UTC, jiromaykin commented
> ...... the second one just bind()'s without arrow function  (and it works because we explicitly bind `this` to the function reference so it has an explicit `this`).

Yes @Bartvaderkin so this should be correct now? There are multiple things not quite right with the Modal from which this is constructed - the time reset doesn't work for the Session modal when a user is typing for example, and the second modal that pops up after clicking, doesn't behave correctly when clicking outside of the button - i will need to rebuild this completely and put it back into draft.

2023-10-03 15:04 UTC, jiromaykin commented
@alextreme @pi-sigma This one could use a thorough testing (not part of the sprint).

2023-10-23 14:41 UTC, pi-sigma requested changes
I no longer see the `Uncaught DOMExceptio` I reported earlier. On the other hand, I'm getting `Uncaught TypeError: this.configureModal is not a function at showExpiredModal` as soon as the session expires. Needs another look

2023-11-27 16:26 UTC, jiromaykin commented
> I no longer see the `Uncaught DOMExceptio` I reported earlier. On the other hand, I'm getting `Uncaught TypeError: this.configureModal is not a function at showExpiredModal` as soon as the session expires. Needs another look

@pi-sigma I think you need to do a proper `Git Pull` and `NPM run watch` - because I do not see these errors anymore.

2023-11-28 13:55 UTC, pi-sigma approved these changes

2023-11-28 14:13 UTC, merged