[#1505] upgrade django-digid-eherkenning to 0.7.0
maykinmedia/open-inwoner pull request #662
Opened 2023-06-08 10:38 UTC by pi-sigma

The upgrade should remove the intermediate screen shown when logging in via DigiD.

Taiga: 1505

2023-06-12 18:28 UTC, alextreme commented
@pi-sigma please assign a reviewer

2023-06-13 07:31 UTC, Bartvaderkin requested changes

2023-06-13 07:31 UTC, Bartvaderkin commented on src/open_inwoner/conf/staging.py
> +DIGID_MOCK = False
Is this necessary for the upgrade?

2023-06-14 07:07 UTC, Bartvaderkin approved these changes

2023-06-14 10:11 UTC, merged