:lipstick: [#1574] Create tab panel template
maykinmedia/open-inwoner pull request #703
Opened 2023-06-26 14:31 UTC by jiromaykin

New design for a new 'component'
https://taiga.maykinmedia.nl/project/open-inwoner/task/1574 
extra: make it accessible and act on Tab key + add translations.

Note to self: eventually need to add the File_list code:

```
<div class="file-list">
    <ul class="file-list__list">
        <li class="file-list__list-item">
            <aside class="file" aria-label="Bestand voorbeeld-cv_spfQqXX">
            {% for report in yearly_benefits %}
                <div class="file__file">
                    {% icon icon="description" aria-hidden=True icon_position="before" primary=True outlined=True %}
                    <p class="p">{{ report }}</p>
                    <a href="{% url 'profile:download_yearly_benefits' file_name=report %}" target="_blank" rel="noopener noreferrer" class="link link--icon link--icon-position-before link--secondary" aria-label="Download" title="Download">
                    <span class="link__text">{% trans "Download" %}</span>
                    {% icon icon="file_download" aria-hidden=True icon_position="before" primary=True outlined=False %}
                    </a>
                </div>
            {% endfor %}
            </aside>
        </li>
    </ul>
</div>
```

<img width="821" alt="Screenshot 2023-07-04 at 11 03 16" src="https://github.com/maykinmedia/open-inwoner/assets/118177951/dbc3fe91-9cff-49c6-b71c-cd76c9094388">

<img width="944" alt="Screenshot 2023-07-11 at 15 14 20" src="https://github.com/maykinmedia/open-inwoner/assets/118177951/edb1e72e-bb08-469c-93b7-d1c371eedfb9">

2023-06-29 11:01 UTC, jiromaykin commented
@vaszig and @pi-sigma with this PR I am not sure when to open this up for review: I'm not sure if the template tag (render_tabs_panel) I made has enough attributes for you to work with. 
- I have added a visible working two-tab example in the 'Mijn vragen' page temporarily so you can preview what it looks like (contains hard-coded mock data from the tag which should be removed)
- and I have added an example page in the SSD directory which I will also remove.

2023-06-29 12:11 UTC, vaszig commented
I think we can't review this until we are sure about what we need (views and templates). Since it's not a generic component (if I understand correctly) let's wait a bit more and tackle this when we have some progress concerning the other tasks which have to do mostly with the backend.

2023-07-03 08:46 UTC, alextreme commented
Discussed with Jiro. At this stage it isn't necessary to have a reusable component, the use case (for now) is specific for Mijn Uitkeringen. If Paul has created the template for this then Jiro can integrate his tab-component for Mijn Uitkeringen

2023-07-03 09:10 UTC, jiromaykin commented
@pi-sigma New information for me is that you actually really only need 1 view for 1 form - so I will have to change this PR in such a way it will become usable for the backend more easily - I will probably need to make it static and have the titles link to a different view? (Right now it takes in multiple panels on 1 page because that's sort of a standard front-end way to do it, but in this case this seems problematic for the back-end).

2023-07-11 12:15 UTC, pi-sigma commented on src/open_inwoner/templates/pages/ssd/yearly_reports_list.html
> +                                </li>
The namespace needs to be changed from `ssd` to `profile` since the urls are exposed via the CMS.

2023-07-11 12:19 UTC, pi-sigma requested changes
Couple minor changes and we're good to go.

2023-07-11 12:59 UTC, jiromaykin commented on src/open_inwoner/scss/components/TabPanel/TabPanel.scss
> +  }
Actually I need to add even MORE breakpoints - this is meant to keep the maximum value of the tabs still look nice if the 'component' would be in fullwidth containers (like: if it wouldn't be inside a render_column) - and I see I need to add more styles to make it fill out nicely on the smallest supported screens (360px).

2023-07-17 15:31 UTC, pi-sigma approved these changes

2023-07-18 06:26 UTC, merged