[#1657] add options to hide categories and search from anonymous users
maykinmedia/open-inwoner pull request #732
Opened 2023-08-14 15:31 UTC by pi-sigma

- added model fields (bool) for hiding categories, search bar + search page
- added `LoginMaybeRequiredMixin` to categories and search views in order to conditionally restrict access to authenticated users

Taiga: [#1657](https://taiga.maykinmedia.nl/project/open-inwoner/task/1657)

2023-08-16 15:51 UTC, alextreme approved these changes
Looks good, however considering the refactor is a bit bigger than only the requested change @jiromaykin should also take a look (and he's back tomorrow)

2023-08-17 08:10 UTC, jiromaykin commented
> ....considering the refactor is a bit bigger than only the requested change @jiromaykin should also take a look...

I will check it out and will need to update everything locally and see what I can do here.

2023-08-17 08:39 UTC, jiromaykin requested changes
All else is looking good, apart from the spellign mistakes; so when logged all have become invisible, both on mobile as well as on desktop.

2023-08-17 08:39 UTC, jiromaykin commented on src/open_inwoner/configurations/migrations/0048_auto_20230816_1255.py
> +                verbose_name="Hide search from anonymouns users",
1st: Spelling mistake: "anonymouns" should be "anonymous"

2023-08-17 08:39 UTC, jiromaykin commented on src/open_inwoner/configurations/models.py
> +        verbose_name=_("Hide categories from anonymouns users"),
2nd occurence: Spelling mistake: "anonymouns" should be "anonymous"

2023-08-17 08:39 UTC, jiromaykin commented on src/open_inwoner/configurations/models.py
> +        verbose_name=_("Hide search from anonymouns users"),
3rd: Spelling mistake: "anonymouns" should be "anonymous"

2023-08-17 15:25 UTC, jiromaykin approved these changes

2023-08-17 16:41 UTC, merged