[#1748] Add option to make product-detail content collapse
maykinmedia/open-inwoner pull request #785
Opened 2023-09-25 18:26 UTC by jiromaykin

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1748
Set Boolean false by default: show content visible as normal.
If checkbox is set: show collapse button.

2023-10-02 10:20 UTC, jiromaykin commented
Note to myself for later translations: 
English is the basis and after translations it will all be like this:
`<a class="readmore__toggle button button--textless button--icon button--icon-after button--secondary button--transparent" href="#" title={% trans "Klik hier om de tekst uit te klappen" %} aria-label={% trans "Klik hier voor meer informatie" %} aria-expanded="false">
                {% icon icon="expand_more" icon_position="after" icon_outlined=True %}
                <span class="readmore__button-text">{% trans "Klik hier voor meer informatie" %}</span>
                <span class="readmore__button-text--hidden">{% trans "Toon minder informatie" %}</span>
            </a>`

2023-10-03 08:29 UTC, alextreme commented on src/open_inwoner/pdc/models/product.py
> +        verbose_name=_("Read more"),
Collapse content

2023-10-03 12:25 UTC, jiromaykin commented
@pi-sigma This one has finally turned 'green' again - so if you want and have the time, you can also review this one (I changed the checkbox labeltext into  'collapse content' now)

2023-10-03 12:58 UTC, alextreme commented on src/open_inwoner/pdc/views.py
> +        context["readmore"] = readmore
You don't really need 'readmore' as intermediate variable:

`context["readmore"] = product.read_more`

And adding this variable manually to the context is also not necessary. You can simply use:

`{% if object.read_more %}` 

in the template. Every DetailView automatically has `object` in the context.

2023-10-03 14:01 UTC, pi-sigma requested changes
Looking good overall. As we discussed, the variable for expanding/collapsing the content should be renamed, though I'll leave it to you if you prefer `content_is_collapsable`, `content_is_expandable`, or sth. like it.

2023-10-03 16:51 UTC, alextreme approved these changes

2023-10-03 16:52 UTC, merged