[#1715] Added management command to delete expired contact invitations
maykinmedia/open-inwoner pull request #787
Opened 2023-09-26 10:00 UTC by pi-sigma

Taiga [#1715](https://taiga.maykinmedia.nl/project/open-inwoner/task/1715)

2023-09-26 14:05 UTC, Bartvaderkin requested changes

2023-09-26 14:34 UTC, pi-sigma commented on src/open_inwoner/accounts/management/commands/delete_invitations.py
> +            },
When I use `system_action` I get an error when passing the `content_object` as argument (it's not expected by `TimeLineLog`). Is this actually used anywhere?

2023-09-28 10:05 UTC, Bartvaderkin requested changes

2023-09-28 10:05 UTC, Bartvaderkin commented on src/open_inwoner/accounts/management/commands/delete_invitations.py
> +            message = f"Expired contact invitations from {user.first_name} {user.last_name} deleted"
*If* we print names we use the methods so we don't forget infixes etc (eg: `user.get_full_name()`).

In this case the name might not be needed as we already set the user on the record. For triage it'd also be helpful to include a count in the message (eg: "Expired N contact invitations')

2023-09-28 10:09 UTC, Bartvaderkin commented on src/open_inwoner/utils/logentry.py
> +        | kwargs,
Note the existing codebase doesn't really use overloaded operators so I'm not convinced we should sprinkle them around in random places. (eg: it is no longer simplistic code)

2023-09-28 14:21 UTC, Bartvaderkin approved these changes

2023-09-28 14:33 UTC, merged