Adding Objects API client integration
maykinmedia/open-inwoner pull request #793
Opened 2023-09-28 14:52 UTC by alextreme

2023-10-06 13:05 UTC, alextreme commented on src/open_inwoner/templates/cms/objects/objects_map.html
> +        {% map 52.1326 5.2913 zoom=3 geojson_feature_collection=objects %}
Zou nog instelbaar gemaakt kunnen worden

2023-10-06 13:06 UTC, alextreme commented on src/open_inwoner/templates/cms/objects/objects_map.html
> +      <p>Er staan geen taken gevonden</p>
Zou nog instelbaar gemaakt kunnen worden

2023-10-06 13:11 UTC, alextreme commented
Dank @bart-maykin voor een mooie eerste integratie van de Objecten API. 

@jiromaykin goed om later deze maand ter voorbereiding op NLDS integratie hier naar te kijken. Bart heeft de stijling overgenomen op basis van:

> Het storybook
> 
> [React / Actions / Action - Link ⋅ Storybook (nl-design-system.github.io)](https://nl-design-system.github.io/denhaag/?path=/docs/react-actions-action--link)
> 
> Github voor de frontend code
> 
> https://github.com/nl-design-system/denhaag

Ik twijfel nog wel wat de volgende stap hiermee wordt. We kunnen het (na wat poetsen) samenvoegen echter aangezien geen van de huidige OIP gemeenten de Objecten API gebruikt voelt het nog prematuur. @Bartvaderkin mag hier ook een blik op werpen

2023-10-24 12:15 UTC, Bartvaderkin requested changes
Looks good, some small notes in the files.

Two other notes:

- [ ] Can you rebase on current development and get rid of the ancient merge commits and other old noise.
- [ ] We try to use '[#1234] Added a thing to fix that other thing' commit messages (eg: uppercase verb, no gitmoji and a useful message)

2023-10-24 12:15 UTC, Bartvaderkin commented on src/open_inwoner/cms/objects/cms_plugins.py
> +                    return "cms/objects/objects_map.html"
The project uses python 3.9 so no pattern matching.

2023-10-24 12:15 UTC, Bartvaderkin commented on src/open_inwoner/components/templates/components/DenhaagAction/DenhaagAction.html
> +            <time datetime="2023-09-28T19:47:36.593Z">{{date}}</time>
Hardcoded datetime.

2023-10-24 12:20 UTC, Bartvaderkin commented on src/open_inwoner/components/templates/components/DenhaagAction/DenhaagAction.html
> +<a href="{{link}}" class="denhaag-action denhaag-action--single">
Why is a lot of this namepaced as 'Den Haag'?

2023-10-24 12:20 UTC, Bartvaderkin commented on src/open_inwoner/components/templatetags/denhaag_action_tags.py
> +    return kwargs
What is 'Den Haag' about this?

2023-10-24 12:22 UTC, Bartvaderkin commented on src/open_inwoner/components/templates/components/DenhaagAction/DenhaagAction.html
> +</a>
Github shows a red no-newline warning here (configure your editor to add it on save).

2024-10-18 13:13 UTC, alextreme commented
Vervangen met https://github.com/maykinmedia/open-inwoner/pull/1442 tijdens de afgelopen hackathon, dank Bart voor de oude PR we hebben er nuttig gebruik van weten te maken

2024-10-18 13:13 UTC, closed without merging