Feature/1829 statustype action button
maykinmedia/open-inwoner pull request #829
Opened 2023-11-01 09:17 UTC by pi-sigma

Taiga [#1829](https://taiga.maykinmedia.nl/project/open-inwoner/task/1829)

The call-to-action button is made configurable per case status type by adding relevant fields to `ZaakTypeStatusTypeConfig`

2023-11-02 10:06 UTC, jiromaykin requested changes

2023-11-02 10:06 UTC, jiromaykin commented on src/open_inwoner/openzaak/tests/test_cases.py
> +            call_to_action_text="yolo",
Perhaps use "Lorem ipsum" here instead :-)

2023-11-02 10:06 UTC, jiromaykin commented on src/open_inwoner/templates/pages/cases/status_inner.html
> +                                            {% if case.internal_upload_enabled or case.external_upload_enabled %}
This works correctly for status that are currently active, for cases that are not finished yet,
but the button doesn't show up in the last status for Cases that are finalized ('Afgehandeld').
Example: for ISBN login nr 111111110: http://127.0.0.1:8000/mijn-aanvragen/5a7520bb-789d-401f-bdc5-e3a2e92cfeee/status/
Maybe it helps to say I am using this kind of code. in order to show things specifically for the last finalized status only:
`{% if not case.end_statustype_data %}LAST{% endif %}`

2023-11-06 15:54 UTC, jiromaykin reviewed
When testing this: the CTA button needs to be visible/configurable for the current AND final active status, (example: ISBNnr: 111111110, and case: http://127.0.0.1:8000/mijn-aanvragen/054847a7-1ccb-4cd4-8768-1fff29f08cf6/status/)
So: a case that is 'Afgehandeld' will show it's current status as Afgehandled, which is also completed/final. This very last status is a bit of a special animal,
but maybe it will show up correctly in the final 'afgehandeld' status once you've rebased this PR on my PR #821 ?

Also: maybe it's possible to make the final Admin table cells a bit less wide? 
 
<img width="1089" alt="Screenshot 2023-11-06 at 16 36 58" src="https://github.com/maykinmedia/open-inwoner/assets/118177951/ee3f4395-9942-4688-abce-858a9fe62b57">

2023-11-07 11:30 UTC, pi-sigma commented
You need to specify a url for the button, otherwise it won't show (a button without url wouldn't do anything). If you fill in `call_to_action_url` and `call_to_action_text`, it works:
 
![Screenshot from 2023-11-07 12-28-12](https://github.com/maykinmedia/open-inwoner/assets/89185369/6f4a8f9d-c10e-460b-931b-8f3a8d9d192b)

2023-11-07 18:27 UTC, jiromaykin commented
> You need to specify a url for the button, otherwise it won't show (a button without url wouldn't do anything). If you fill in `call_to_action_url` and `call_to_action_text`

Yes, this works - before I approve you may have to remove all of the frontend template code and the styling, or else you're going to have endless merge-conflicts when rebasing, I'd think.

2023-11-14 10:28 UTC, alextreme commented
@pi-sigma feel free to resolve the conflicts and assign me to review

2023-11-15 09:34 UTC, alextreme commented on src/open_inwoner/openzaak/models.py
> +        help_text=_("Wheter document uploads are to be shown"),
*whether

2023-11-15 09:34 UTC, alextreme commented on src/open_inwoner/openzaak/tests/factories.py
> +    # call_to_action_url = statustype_url
to remove?

2023-11-15 09:35 UTC, alextreme approved these changes
2 trivial remarks, after that this can be merged in my eyes

2023-11-15 16:44 UTC, alextreme approved these changes

2023-11-15 16:45 UTC, merged