[#1843] Add description field to ZaakTypeStatusTypeConfig
maykinmedia/open-inwoner pull request #841
Opened 2023-11-09 10:00 UTC by pi-sigma

Taiga [#1843](https://taiga.maykinmedia.nl/project/open-inwoner/task/1843)

2023-11-09 10:12 UTC, pi-sigma commented
As with other recent additions, our tabular inlines for zaak-related configurations are getting quite wide. @jiromaykin asked if it was possible to at least restrict the size of the widget. For textarea widgets, that's easily done. For the `CKEditorWidget` it's different. The width is set in `scss/admin/_ck_editor.scss` to `624px !important;` ruling out programmatic overrides. I leave the styling it as is for now. Perhaps we can discuss during the next weekly if this should be addressed.

2023-11-09 11:23 UTC, stevenbal requested changes
Regarding the wide inlines, I think it's better to switch to from `admin.TabularInline` to `admin.StackedInline` for `ZaakTypeStatusTypeConfigInline` (and I think this would be better for `ZaakTypeResultaattypeConfigInline` as well

2023-11-09 11:23 UTC, stevenbal commented on src/open_inwoner/openzaak/models.py
> +            "The text displayed in the list view for cases with this statustype"
```suggestion
            "The text displayed in the case detail page for the status with this statustype"
```

2023-11-09 12:53 UTC, alextreme commented
@pi-sigma please do

2023-11-13 08:58 UTC, stevenbal approved these changes

2023-11-13 08:59 UTC, merged