:bug: [#1961] Implement redirect after DigiD/eHerkenning OIDC login
maykinmedia/open-inwoner pull request #960
Opened 2024-01-15 16:37 UTC by stevenbal

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1961

TODO:
- [ ] doesn't work for eherkenning due to branches select
- [ ] not sure about redirect after necessary fields screen
- [ ] add tests?

2024-01-16 13:02 UTC, stevenbal commented
@alextreme I'll leave this for now, the whole middleware redirect thing is getting too complicated (hence the failing tests)

2024-01-16 13:52 UTC, alextreme commented
Agreed, lets take a look together at a later stage and discuss with @pi-sigma what a better approach would be

2024-02-26 08:50 UTC, Bartvaderkin requested changes

2024-02-26 08:50 UTC, Bartvaderkin commented on src/open_inwoner/accounts/views/registration.py
> +            return self.request.GET["next"]
Here we need a `is_safe_url` (or in Django 4.0 `url_has_allowed_host_and_scheme`) to protect against unsafe redirects

2024-02-27 08:05 UTC, Bartvaderkin approved these changes

2024-03-04 09:54 UTC, merged