:sparkles: [#2024] Split email templates for zaak status/document notification
maykinmedia/open-inwoner pull request #975
Opened 2024-01-19 14:55 UTC by stevenbal

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/2024

2024-01-19 15:55 UTC, pi-sigma requested changes

2024-01-19 15:55 UTC, pi-sigma commented on src/open_inwoner/conf/parts/maileditor.py
> +            <p>Met vriendelijke groet,
This is Dutch, the previous text is English. I suggest the entire default message should be Dutch, since it is client-facing.

2024-01-19 15:55 UTC, pi-sigma commented on src/open_inwoner/conf/parts/maileditor.py
> +            <p>You are receiving this email because one of your cases received a new document attachment.</p>
See previous comment

2024-01-22 11:39 UTC, pi-sigma approved these changes

2024-01-22 15:03 UTC, alextreme approved these changes

2024-01-22 15:03 UTC, merged