:sparkles: [#2025] Daily email digest to inform admins about failed emails
maykinmedia/open-inwoner pull request #976
Opened 2024-01-19 16:26 UTC by stevenbal

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/2025

2024-01-22 15:52 UTC, pi-sigma requested changes

2024-01-22 15:52 UTC, pi-sigma commented on src/open_inwoner/configurations/management/commands/send_failed_mail_digest.py
> +logger = logging.getLogger(__name__)
You're defining a logger but then only write to `stdout`. You can either get rid of the logger or use it in the `handle`.

2024-01-22 16:21 UTC, pi-sigma approved these changes

2024-01-29 14:40 UTC, alextreme approved these changes
Please also add a PR cronjobs.conf in deployment, otherwise I'll overlook it: https://bitbucket.org/maykinmedia/maykin-deployment/src/master/projects/open-inwoner/cronjobs.conf

2024-01-29 14:40 UTC, merged